S3BucketEventRule:
  Type: AWS::Events::Rule
  Properties:
    EventBusName: default
    EventPattern:
      source:
        - aws.s3
      detail-type:
        - AWS API Call via CloudTrail
      detail:
        eventSource:
          - s3.amazonaws.com
        eventName:
          - prefix: CreateBucket
          - prefix: PutBucket
          - prefix: DeleteBucket
    Name: port-aws-exporter-sync-s3-trails
    State: ENABLED
    Targets:
      - Id: PortAWSExporterEventsQueue
        Arn:
          Fn::ImportValue:
            Fn::Sub: ${PortAWSExporterStackName}-EventsQueueARN
        InputTransformer:
          InputPathsMap:
            awsRegion: $.detail.awsRegion
            eventName: $.detail.eventName
            requestBucketName: $.detail.requestParameters.bucketName
          InputTemplate: |-
            {
              "resource_type": "AWS::S3::Bucket",
              "region": "\"<awsRegion>\"",
              "identifier": "\"<requestBucketName>\"",
              "action": "if \"<eventName>\" | test(\"DeleteBucket[^a-zA-Z]*$\") then \"delete\" else \"upsert\" end"
            }