name: Terraform Format and Commit

on:
  pull_request:
    paths:
      - "**/*.tf"

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Run Terraform Format
        run: |
          terraform fmt aws -recursive

      - name: Run Terraform Format Check and Commit Changes
        run: |
          if ! terraform fmt --recursive -check; then
            terraform fmt --recursive
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git commit -m "Apply terraform fmt"
            git push origin $(git symbolic-ref --short HEAD)
          else
            echo "Code is already properly formatted"
          fi
